### ISSUE TITLE
docker publish fails with "404 Not Found"

### ISSUE THREAD

**Issue by larshp** [exercism/abap-test-runner#11]
see https://github.com/exercism/abap-test-runner/runs/4321543628?check_suite_focus=true

@ErikSchierboom can you help?

**Comment by ErikSchierboom** [comment]
I tagged you in https://github.com/exercism/terraform/pull/66, which will fix this!

**Comment by ErikSchierboom** [comment]
Passing now: https://github.com/exercism/abap-test-runner/actions/runs/1502872526
