### ISSUE TITLE
Github actions: Adding credentials/secrets for docker image publish

### ISSUE THREAD

**Issue by larshp** [exercism/abap-test-runner#8]
see error in
https://github.com/exercism/abap-test-runner/runs/4308288046?check_suite_focus=true

**Comment by ErikSchierboom** [comment]
@iHiD This one's for you :)

**Comment by iHiD** [comment]
Should be done :)

**Comment by larshp** [comment]
is there one of you/someone else that would like to review https://github.com/exercism/abap-test-runner/pull/7 before it is merged? merging it should publish the first docker images

**Comment by iHiD** [comment]
I'll leave that to @ErikSchierboom
