### ISSUE TITLE
github settings changes -> admin

### ISSUE THREAD

**Issue by larshp** [exercism/abap-test-runner#87]
@iHiD can you help updating below for this repository,

- [x] set branch `main` to protected
- [x] remove the projects view
- [x] remove the wiki view
- [ ] remove releases on front page
- [ ] remove packages on front page
- [x] set "always suggest update branch"
- [ ] set "auto delete branch after merge"

**Comment by larshp** [comment]
@iHiD can you help to setup above list

the merge https://github.com/exercism/abap-test-runner/pull/93, by @ErikSchierboom broke the runner, CI correctly failed and should have blocked the merge

**Comment by mbtools** [comment]
you also might want to add some of these settings like "branch protection" to the setup instructions for new tracks 😃

**Comment by ErikSchierboom** [comment]
@larshp Sorry about that! I didn't actually mean to merge this, just to approve :(

**Comment by iHiD** [comment]
All done :)
