### ISSUE TITLE
Test runner failure

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/abap-test-runner#95]
As per https://twitter.com/luidepri/status/1517449646297305089:

> When i try to Run Test , it returns you this Error Message  even with exercise alredy solved.
> 
> Same thing when you try to run tests just with the template of the script.

![image](https://user-images.githubusercontent.com/135246/164709448-39dd3a8f-82a7-40e8-a0fe-08f2809fb195.png)

**Comment by larshp** [comment]
I replied on twitter, suggest closing this issue and moving it to https://github.com/exercism/abap/issues/143
